version: "3.8"
services:
  database-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: database-api
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DATABASE_USER: postgres
      DATABASE_URI: ${DATABASE_URI:-postgresql://postgres:postgres@database_db:5432/cranecloud_db}
      TEST_DATABASE_URI: ${TEST_DATABASE_URI:-postgresql://postgres:postgres@database_db:5432/cranecloud_db_test}
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
    depends_on:
      - database_db

  database_db:
    restart: always
    image: postgres:10.8-alpine
    container_name: postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cranecloud_db
    ports:
      - "4200:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
