version: "3.8"
services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  database-api:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: database-api
    environment:
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
      DATABASE_USER: postgres
      ADMIN_MYSQL_USER: ${ADMIN_MYSQL_USER}
      ADMIN_MYSQL_HOST: ${ADMIN_MYSQL_HOST}
      ADMIN_MYSQL_PORT: ${ADMIN_MYSQL_PORT}
      ADMIN_MYSQL_PASSWORD: ${ADMIN_MYSQL_PASSWORD}
      ADMIN_PSQL_HOST: ${ADMIN_PSQL_HOST}
      ADMIN_PSQL_USER: ${ADMIN_PSQL_USER}
      ADMIN_PSQL_PASSWORD: ${ADMIN_PSQL_PASSWORD}
      ADMIN_PSQL_PORT: ${ADMIN_PSQL_PORT}
      DATABASE_URI: ${DATABASE_URI:-postgresql://postgres:postgres@database_db:5432/cranecloud_db}
      TEST_DATABASE_URI: ${TEST_DATABASE_URI:-postgresql://postgres:postgres@database_db:5432/cranecloud_db_test}
      JWT_SALT: ${JWT_SALT}
      MAIL_USERNAME: ${MAIL_USERNAME:-no-reply@cranecloud.io}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
    depends_on:
      - database_db

  database_db:
    restart: always
    image: postgres:10.8-alpine
    container_name: postgres-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cranecloud_db
    ports:
      - "${DATABASE_SERVICE_PORT:-4200}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  celery_worker:
    container_name: celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run celery -A main.celery worker --loglevel=info 
    environment:
      DATABASE_URI: ${DATABASE_URI:-postgresql://postgres:postgres@database_db:5432/cranecloud_db}
      MAIL_USERNAME: ${MAIL_USERNAME:-no-reply@cranecloud.io}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    volumes:
      - .:/app
    depends_on:
      - redis
      - database-api
  
  celery_beat:
    container_name: celery_beat_scheduler
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run celery -A main.celery beat --loglevel=info
    environment:
      DATABASE_URI: ${DATABASE_URI:-postgresql://postgres:postgres@database_db:5432/cranecloud_db}
      MAIL_USERNAME: ${MAIL_USERNAME:-no-reply@cranecloud.io}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    depends_on:
      - redis
    volumes:
      - .:/app

  celery_flower:
    container_name: celery_flower
    build: .
    command: poetry run celery -A main.celery flower --port=5555
    ports:
      - 5556:5555
    environment:
      DATABASE_URI: ${DATABASE_URI:-postgresql://postgres:postgres@database_db:5432/cranecloud_db}
      MAIL_USERNAME: ${MAIL_USERNAME:-no-reply@cranecloud.io}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      REDIS_URL: ${REDIS_URL:-redis://redis:6379}
    depends_on:
      - database-api
      - redis
      - celery_worker

volumes:
  db-data: