"""empty message

Revision ID: 37ec41722d1b
Revises: 718da4a88cdd
Create Date: 2024-03-14 10:48:49.326288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37ec41722d1b'
down_revision: Union[str, None] = '718da4a88cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_databases', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_databases', 'email')
    # ### end Alembic commands ###
