"""add project id

Revision ID: 703c44143fec
Revises: ee15b2e5ac61
Create Date: 2024-08-12 15:50:06.935408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '703c44143fec'
down_revision: Union[str, None] = 'ee15b2e5ac61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_databases', sa.Column('project_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_databases', 'project_id')
    # ### end Alembic commands ###

