"""empty message

Revision ID: 718da4a88cdd
Revises: 
Create Date: 2024-03-05 00:21:14.252201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '718da4a88cdd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_databases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database_flavour_name', sa.String(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('admin_disabled', sa.Boolean(), nullable=True),
    sa.Column('default_storage_kb', sa.BigInteger(), nullable=True),
    sa.Column('allocated_size_kb', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_databases_id'), 'user_databases', ['id'], unique=False)
    op.create_index(op.f('ix_user_databases_owner_id'), 'user_databases', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_databases_owner_id'), table_name='user_databases')
    op.drop_index(op.f('ix_user_databases_id'), table_name='user_databases')
    op.drop_table('user_databases')
    # ### end Alembic commands ###
