"""empty message

Revision ID: ee15b2e5ac61
Revises: 37ec41722d1b
Create Date: 2024-03-14 19:27:45.928450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee15b2e5ac61'
down_revision: Union[str, None] = '37ec41722d1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_databases', sa.Column('notified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_databases', 'notified')
    # ### end Alembic commands ###
