replicaCount: 1

image:
  # repository: gcr.io/crane-cloud-274413/cranecloud-database-api
  repository: mubangizi/database-api
  pullPolicy: Always
  # tag: ${{ DOCKER_IMAGE_TAG }}
  tag: latest

imagePullSecrets: []

nameOverride: "database-api"

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 80

resources: {}
  # limits:
  #   cpu: 512m
  #   memory: 512Mi
  # requests:
  #   cpu: 512m
  #   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}

nginxConf:
  server {
        listen 80;

        location / {
            proxy_pass http://localhost:8000/;
        }
    }

environment:
  FASTAPI_ENV: production
  # DATABASE_URI: ${{ DATABASE_URI }}
  # JWT_SALT: ${{ JWT_SALT }}
  ADMIN_MYSQL_USER: ${{ ADMIN_MYSQL_USER }}
  ADMIN_MYSQL_PASSWORD: ${{ ADMIN_MYSQL_PASSWORD }}
  ADMIN_MYSQL_HOST: ${{ ADMIN_MYSQL_HOST }}
  ADMIN_MYSQL_PORT: ${{ ADMIN_MYSQL_PORT }}
  ADMIN_PSQL_USER: ${{ ADMIN_PSQL_USER }}
  ADMIN_PSQL_PASSWORD: ${{ ADMIN_PSQL_PASSWORD }}
  ADMIN_PSQL_HOST: ${{ ADMIN_PSQL_HOST }}
  ADMIN_PSQL_PORT: ${{ ADMIN_PSQL_PORT }}

  JWT_SALT: "LS0tLQpNSUlFb3dJQkFBS0NBUUVBeENCMk"
  DATABASE_URI: postgresql://mgfygqxffahnalwp:7hx#,W^prBhrVwpBndB6yDd_1C%hbogN@102.134.147.233:32761/eybsyqyftilqwepfdteeesnd
  

celery:
  create: false
  command: ''
